// Battalla TCG - Centralized Card Database
// This file contains all card data and filter options used across the site

const cardsData = [
  { name: "Zeus", type: "greek", category: "hero", subtype: "warrior", trait: "", set: "set1", image: "./images/Cards/Set1/Blue/Hero/Zeus.png" },
  { name: "Poseidon", type: "greek", category: "hero", subtype: "warrior", trait: "", set: "set1", image: "./images/Cards/Set1/Blue/Hero/Poseidon.png" },
  { name: "Hades", type: "greek", category: "hero", subtype: "warrior", trait: "", set: "set1", image: "./images/Cards/Set1/Blue/Hero/Hades.png" },
  { name: "Athena", type: "greek", category: "hero", subtype: "warrior", trait: "", set: "set1", image: "./images/Cards/Set1/Blue/Hero/Athena.png" },
  { name: "Sutoko Teno", type: "yamato", category: "hero", subtype: "yokai", trait: "", set: "set1", image: "./images/Cards/Set1/Purple/Hero/Sutoko_Teno.png" },
  { name: "Shuten Doji", type: "yamato", category: "hero", subtype: "yokai", trait: "", set: "set1", image: "./images/Cards/Set1/Purple/Hero/Shuten_Doji.png" },
  { name: "Sojobo Tengu", type: "yamato", category: "hero", subtype: "yokai", trait: "", set: "set1", image: "./images/Cards/Set1/Purple/Hero/Sojobo_Tengu.png" },
  { name: "Tamamo No Mae", type: "yamato", category: "hero", subtype: "yokai", trait: "", set: "set1", image: "./images/Cards/Set1/Purple/Hero/Tamamo_No_Mae.png" },
  { name: "Horus", type: "egyptian", category: "hero", subtype: "warrior", trait: "", set: "set1", image: "./images/Cards/Set1/Gold/Hero/Horus.png" },
  { name: "Isis", type: "egyptian", category: "hero", subtype: "warrior", trait: "", set: "set1", image: "./images/Cards/Set1/Gold/Hero/Isis.png" },
  { name: "Nephthys", type: "egyptian", category: "hero", subtype: "warrior", trait: "", set: "set1", image: "./images/Cards/Set1/Gold/Hero/Nephthys.png" },
  { name: "Osiris", type: "egyptian", category: "hero", subtype: "warrior", trait: "", set: "set1", image: "./images/Cards/Set1/Gold/Hero/Osiris.png" },
  { name: "Conchobar mac Nessa", type: "celt", category: "hero", subtype: "warrior", trait: "", set: "set1", image: "./images/Cards/Set1/Green/Hero/Conchobar mac Nessa.png" },
  { name: "Blood Rage CuChulainn", type: "celt", category: "hero", subtype: "warrior", trait: "", set: "set1", image: "./images/Cards/Set1/Green/Hero/Blood Rage CuChulainn.png" },
  { name: "CuChulainn", type: "celt", category: "hero", subtype: "warrior", trait: "", set: "set1", image: "./images/Cards/Set1/Green/Hero/CuChulainn.png" },
  { name: "Lugh of the Long Arm", type: "celt", category: "hero", subtype: "fae", trait: "", set: "set1", image: "./images/Cards/Set1/Green/Hero/Lugh of the Long Arm.png" },
  { name: "Danu, Mother of Fae", type: "celt", category: "hero", subtype: "fae", trait: "", set: "set1", image: "./images/Cards/Set1/Green/Hero/Danu, Mother of Fae.png" },
  { name: "Ancient Notes", type: "", category: "assist", subtype: "", trait: "", set: "set1", image: "./images/Cards/Set1/Assist/Ancient Notes.png" },
  { name: "Second Chance", type: "", category: "assist", subtype: "", trait: "", set: "set1", image: "./images/Cards/Set1/Assist/Second Chance.png" },
  { name: "Painful Price", type: "", category: "assist", subtype: "", trait: "", set: "set1", image: "./images/Cards/Set1/Assist/Painful Price.png" },
  { name: "Legends Retold", type: "", category: "assist", subtype: "", trait: "", set: "set1", image: "./images/Cards/Set1/Assist/Legends Retold.png" },
  { name: "Hero Calling", type: "", category: "assist", subtype: "", trait: "", set: "set1", image: "./images/Cards/Set1/Assist/Hero Calling.png" },
  { name: "Potion of Memories", type: "item", category: "assist", subtype: "", trait: "", set: "set1", image: "./images/Cards/Set1/Assist/Potion of Memories.png" },
  { name: "Castor", type: "greek", category: "unit", subtype: "warrior", trait: "", set: "set1", image: "./images/Cards/Set1/Blue/Greek/Castor.png" },
  { name: "Herakles", type: "greek", category: "unit", subtype: "warrior", trait: "", set: "set1", image: "./images/Cards/Set1/Blue/Greek/Herakles.png" },
  { name: "Jason", type: "greek", category: "unit", subtype: "warrior", trait: "", set: "set1", image: "./images/Cards/Set1/Blue/Greek/Jason.png" },
  { name: "Polydeuces", type: "greek", category: "unit", subtype: "warrior", trait: "", set: "set1", image: "./images/Cards/Set1/Blue/Greek/Polydeuces.png" },
  { name: "Orpheus", type: "greek", category: "unit", subtype: "scholar", trait: "", set: "set1", image: "./images/Cards/Set1/Blue/Greek/Orpheus.png" },
  { name: "Asclepius", type: "greek", category: "unit", subtype: "scholar", trait: "", set: "set1", image: "./images/Cards/Set1/Blue/Greek/Asclepius.png" },
  { name: "Daedalus", type: "greek", category: "unit", subtype: "scholar", trait: "", set: "set1", image: "./images/Cards/Set1/Blue/Greek/Daedalus.png" },
  { name: "Moirai Clotho", type: "greek", category: "unit", subtype: "scholar", trait: "", set: "set1", image: "./images/Cards/Set1/Blue/Greek/Moirai Clotho.png" },
  { name: "The Oracle of Delphi", type: "greek", category: "unit", subtype: "scholar", trait: "", set: "set1", image: "./images/Cards/Set1/Blue/Greek/The Oracle of Delphi.png" },
  { name: "Campe", type: "greek", category: "unit", subtype: "beast", trait: "", set: "set1", image: "./images/Cards/Set1/Blue/Greek/Campe.png" },
  { name: "Cerberus", type: "greek", category: "unit", subtype: "beast", trait: "", set: "set1", image: "./images/Cards/Set1/Blue/Greek/Cerberus.png" },
  { name: "Cyclops", type: "greek", category: "unit", subtype: "beast", trait: "", set: "set1", image: "./images/Cards/Set1/Blue/Greek/Cyclops.png" },
  { name: "Hydra", type: "greek", category: "unit", subtype: "beast", trait: "", set: "set1", image: "./images/Cards/Set1/Blue/Greek/Hydra.png" },
  { name: "Siren", type: "greek", category: "unit", subtype: "beast", trait: "", set: "set1", image: "./images/Cards/Set1/Blue/Greek/Siren.png" },
  { name: "Charon's Ferry", type: "greek", category: "assist", subtype: "", trait: "", set: "set1", image: "./images/Cards/Set1/Blue/Greek/Charons Ferry.png" },
  { name: "Hermes' Sandals", type: "greek", category: "assist", subtype: "", trait: "", set: "set1", image: "./images/Cards/Set1/Blue/Greek/Hermes Sandals.png" },
  { name: "Zeus' Lightning Bolt", type: "greek", category: "assist", subtype: "", trait: "", set: "set1", image: "./images/Cards/Set1/Blue/Greek/Zeus Lightning Bolt.png" },
  { name: "Hydra's Poison", type: "greek", category: "assist", subtype: "item", trait: "", set: "set1", image: "./images/Cards/Set1/Blue/Greek/Hydras Poison.png" },
  { name: "Poseidon's Trident", type: "greek", category: "assist", subtype: "item", trait: "", set: "set1", image: "./images/Cards/Set1/Blue/Greek/Poseidons Trident.png" },
  { name: "Elysium", type: "greek", category: "field", subtype: "", trait: "", set: "set1", image: "./images/Cards/Set1/Blue/Greek/Elysium.png" },
  { name: "Underworld", type: "greek", category: "field", subtype: "", trait: "", set: "set1", image: "./images/Cards/Set1/Blue/Greek/Underworld.png" },
  { name: "Aaru- Field of Reeds", type: "egyptian", category: "field", subtype: "", trait: "", set: "set1", image: "./images/Cards/Set1/Gold/Egyptian/Aaru- Field of Reeds.png" },
  { name: "Amulet of Resurrection", type: "egyptian", category: "assist", subtype: "", trait: "", set: "set1", image: "./images/Cards/Set1/Gold/Egyptian/Amulet of Resurrection.png" },
  { name: "Ammit The Devourer", type: "egyptian", category: "unit", subtype: "beast", trait: "", set: "set1", image: "./images/Cards/Set1/Gold/Egyptian/Ammit The Devourer.png" },
  { name: "Ankh- Amulet of Life", type: "egyptian", category: "assist", subtype: "", trait: "", set: "set1", image: "./images/Cards/Set1/Gold/Egyptian/Ankh- Amulet of Life.png" },
  { name: "Apep- The Demon of Chaos", type: "egyptian", category: "unit", subtype: "beast", trait: "", set: "set1", image: "./images/Cards/Set1/Gold/Egyptian/Apep- The Demon of Chaos.png" },
  { name: "Awaken Mummy", type: "egyptian", category: "unit", subtype: "beast", trait: "", set: "set1", image: "./images/Cards/Set1/Gold/Egyptian/Awaken Mummy.png" },
  { name: "Blessings of the Nile", type: "egyptian", category: "assist", subtype: "", trait: "", set: "set1", image: "./images/Cards/Set1/Gold/Egyptian/Blessings of the Nile.png" },
  { name: "Collective Undead", type: "egyptian", category: "unit", subtype: "beast", trait: "", set: "set1", image: "./images/Cards/Set1/Gold/Egyptian/Collective Undead.png" },
  { name: "El Naddaha of the Nile", type: "egyptian", category: "unit", subtype: "beast", trait: "", set: "set1", image: "./images/Cards/Set1/Gold/Egyptian/El Naddaha of the Nile.png" },
  { name: "Eye of Horus", type: "egyptian", category: "assist", subtype: "", trait: "", set: "set1", image: "./images/Cards/Set1/Gold/Egyptian/Eye of Horus.png" },
  { name: "Eye of Ra", type: "egyptian", category: "assist", subtype: "", trait: "", set: "set1", image: "./images/Cards/Set1/Gold/Egyptian/Eye of Ra.png" },
  { name: "False Door", type: "egyptian", category: "assist", subtype: "", trait: "", set: "set1", image: "./images/Cards/Set1/Gold/Egyptian/False Door.png" },
  { name: "Fish of Abta", type: "egyptian", category: "unit", subtype: "beast", trait: "", set: "set1", image: "./images/Cards/Set1/Gold/Egyptian/Fish of Abta.png" },
  { name: "Fragments of Osiris", type: "egyptian", category: "assist", subtype: "", trait: "", set: "set1", image: "./images/Cards/Set1/Gold/Egyptian/Fragments of Osiris.png" },
  { name: "Great Sphinx", type: "egyptian", category: "unit", subtype: "beast", trait: "", set: "set1", image: "./images/Cards/Set1/Gold/Egyptian/Great Sphinx.png" },
  { name: "Jackal Head of the First Gate", type: "egyptian", category: "unit", subtype: "beast", trait: "", set: "set1", image: "./images/Cards/Set1/Gold/Egyptian/Jackal Head of the First Gate.png" },
  { name: "Majestic Griffin", type: "egyptian", category: "unit", subtype: "beast", trait: "", set: "set1", image: "./images/Cards/Set1/Gold/Egyptian/Majestic Griffin.png" },
  { name: "Ram Head of the First Gate", type: "egyptian", category: "unit", subtype: "beast", trait: "", set: "set1", image: "./images/Cards/Set1/Gold/Egyptian/Ram Head of the First Gate.png" },
  { name: "Twin Lions Akher", type: "egyptian", category: "unit", subtype: "beast", trait: "", set: "set1", image: "./images/Cards/Set1/Gold/Egyptian/Twin Lions Akher.png" },
  { name: "Uraeus", type: "egyptian", category: "unit", subtype: "beast", trait: "", set: "set1", image: "./images/Cards/Set1/Gold/Egyptian/Uraeus.png" },
  { name: "Chulainn", type: "celt", category: "unit", subtype: "warrior", trait: "", set: "set1", image: "./images/Cards/Set1/Green/Celt/Chulainn.png" },
  { name: "Finegas", type: "celt", category: "unit", subtype: "warrior", trait: "", set: "set1", image: "./images/Cards/Set1/Green/Celt/Finegas.png" },
  { name: "Fintan", type: "celt", category: "unit", subtype: "warrior", trait: "", set: "set1", image: "./images/Cards/Set1/Green/Celt/Fintan.png" },
  { name: "Fionn", type: "celt", category: "unit", subtype: "warrior", trait: "", set: "set1", image: "./images/Cards/Set1/Green/Celt/Fionn.png" },
  { name: "Macha", type: "celt", category: "unit", subtype: "warrior", trait: "", set: "set1", image: "./images/Cards/Set1/Green/Celt/Macha.png" },
  { name: "Scathach", type: "celt", category: "unit", subtype: "warrior", trait: "", set: "set1", image: "./images/Cards/Set1/Green/Celt/Scathach.png" },
  { name: "Setante", type: "celt", category: "unit", subtype: "warrior", trait: "", set: "set1", image: "./images/Cards/Set1/Green/Celt/Setante.png" },
  { name: "Corra", type: "celt", category: "unit", subtype: "fae", trait: "", set: "set1", image: "./images/Cards/Set1/Green/Celt/Corra.png" },
  { name: "Far Darrig", type: "celt", category: "unit", subtype: "fae", trait: "", set: "set1", image: "./images/Cards/Set1/Green/Celt/Far Darrig.png" },
  { name: "Gancanagh", type: "celt", category: "unit", subtype: "fae", trait: "", set: "set1", image: "./images/Cards/Set1/Green/Celt/Gancanagh.png" },
  { name: "Lugh", type: "celt", category: "unit", subtype: "fae", trait: "", set: "set1", image: "./images/Cards/Set1/Green/Celt/Lugh.png" },
  { name: "Pooka (Dog Form)", type: "celt", category: "unit", subtype: "fae", trait: "", set: "set1", image: "./images/Cards/Set1/Green/Celt/Pooka (Dog Form).png" },
  { name: "Pooka (Human Form)", type: "celt", category: "unit", subtype: "fae", trait: "", set: "set1", image: "./images/Cards/Set1/Green/Celt/Pooka (Human Form).png" },
  { name: "Pooka (True Form)", type: "celt", category: "unit", subtype: "fae", trait: "", set: "set1", image: "./images/Cards/Set1/Green/Celt/Pooka (True Form).png" },
  { name: "Salmon of Wisdom", type: "celt", category: "unit", subtype: "beast", trait: "", set: "set1", image: "./images/Cards/Set1/Green/Celt/Salmon of Wisdom.png" },
  { name: "Blessing of the Dahnnan", type: "celt", category: "assist", subtype: "", trait: "", set: "set1", image: "./images/Cards/Set1/Green/Celt/Blessing of the Dahnnan.png" },
  { name: "Druid's Foresight", type: "celt", category: "assist", subtype: "", trait: "", set: "set1", image: "./images/Cards/Set1/Green/Celt/Druids Foresight.png" },
  { name: "Fuamnach's Scheme", type: "celt", category: "assist", subtype: "", trait: "", set: "set1", image: "./images/Cards/Set1/Green/Celt/Fuamnach's Scheme.png" },
  { name: "Gae Bulg", type: "celt", category: "assist", subtype: "", trait: "", set: "set1", image: "./images/Cards/Set1/Green/Celt/Gae Bulg.png" },
  { name: "Hound of Chulainn", type: "celt", category: "assist", subtype: "", trait: "", set: "set1", image: "./images/Cards/Set1/Green/Celt/Hound of Chulainn.png" },
  { name: "Pooka Mischief", type: "celt", category: "assist", subtype: "", trait: "", set: "set1", image: "./images/Cards/Set1/Green/Celt/Pooka Mischief.png" },
  { name: "Shape Change", type: "celt", category: "assist", subtype: "", trait: "", set: "set1", image: "./images/Cards/Set1/Green/Celt/Shape Change.png" },
  { name: "Tir na Nog", type: "celt", category: "field", subtype: "", trait: "", set: "set1", image: "./images/Cards/Set1/Green/Celt/Tir na Nog.png" },
  { name: "Yokai Parade", type: "yamato", category: "field", subtype: "yokai", trait: "", set: "set1", image: "./images/Cards/Set1/Purple/Yamato/Yokai Parade.png" },
  { name: "Taizan Fukunsai", type: "yamato", category: "assist", subtype: "yokai", trait: "", set: "set1", image: "./images/Cards/Set1/Purple/Yamato/Taizan Fukunsai.png" },
  { name: "Tengu Shogi Game", type: "yamato", category: "assist", subtype: "yokai", trait: "", set: "set1", image: "./images/Cards/Set1/Purple/Yamato/Tengu Shogi Game.png" },
  { name: "Shikigami Parade", type: "yamato", category: "assist", subtype: "", trait: "", set: "set1", image: "./images/Cards/Set1/Purple/Yamato/Shikigami Parade.png" },
  { name: "Restful Tengu", type: "yamato", category: "unit", subtype: "yokai", trait: "", set: "set1", image: "./images/Cards/Set1/Purple/Yamato/Restful Tengu.png" },
  { name: "Neglected Items", type: "yamato", category: "assist", subtype: "yokai", trait: "", set: "set1", image: "./images/Cards/Set1/Purple/Yamato/Neglected Items.png" },
  { name: "Onibi", type: "yamato", category: "unit", subtype: "yokai", trait: "", set: "set1", image: "./images/Cards/Set1/Purple/Yamato/Onibi.png" },
  { name: "Boroboroton", type: "yamato", category: "unit", subtype: "yokai", trait: "item", set: "set1", image: "./images/Cards/Set1/Purple/Yamato/Boroboroton.png" },
  { name: "Ashiya Doman", type: "yamato", category: "unit", subtype: "onmyoji", trait: "", set: "set1", image: "./images/Cards/Set1/Purple/Yamato/Ashiya Doman.png" },
  { name: "Minamoto No Yorimitsu", type: "yamato", category: "unit", subtype: "onmyoji", trait: "", set: "set1", image: "./images/Cards/Set1/Purple/Yamato/Minamoto No Yorimitsu.png" },
  { name: "Kuda-Ya", type: "yamato", category: "unit", subtype: "onmyoji", trait: "", set: "set1", image: "./images/Cards/Set1/Purple/Yamato/Kuda-Ya.png" },
  { name: "ChoChin Obake", type: "yamato", category: "unit", subtype: "yokai", trait: "item", set: "set1", image: "./images/Cards/Set1/Purple/Yamato/ChoChin Obake.png" },
  { name: "Ittan Momen", type: "yamato", category: "unit", subtype: "yokai", trait: "item", set: "set1", image: "./images/Cards/Set1/Purple/Yamato/Ittan Momen.png" },
  { name: "Kasa Obake", type: "yamato", category: "unit", subtype: "yokai", trait: "item", set: "set1", image: "./images/Cards/Set1/Purple/Yamato/Kasa Obake.png" },
  { name: "Mokumokuren", type: "yamato", category: "unit", subtype: "yokai", trait: "item", set: "set1", image: "./images/Cards/Set1/Purple/Yamato/Mokumokuren.png" },
  { name: "Yamaoroshi", type: "yamato", category: "unit", subtype: "yokai", trait: "item", set: "set1", image: "./images/Cards/Set1/Purple/Yamato/Yamaoroshi.png" },
  { name: "Inugami", type: "yamato", category: "unit", subtype: "yokai", trait: "shikigami", set: "set1", image: "./images/Cards/Set1/Purple/Yamato/Inugami.png" },
  { name: "Kudagitsune", type: "yamato", category: "unit", subtype: "yokai", trait: "shikigami", set: "set1", image: "./images/Cards/Set1/Purple/Yamato/Kudagitsune.png" },
  { name: "Paper Shikigami", type: "yamato", category: "unit", subtype: "yokai", trait: "shikigami", set: "set1", image: "./images/Cards/Set1/Purple/Yamato/Paper Shikigami.png" },
];

// Filter configuration - organized by category
const filterConfig = {
  sets: [
    { label: "Set 1", value: "set1" }
  ],
  cardTypes: [
    { label: "Hero", value: "hero" },
    { label: "Unit", value: "unit" },
    { label: "Assist", value: "assist" },
    { label: "Field", value: "field" },
    { label: "Item", value: "item" }
  ],
  factions: [
    { label: "Greek", value: "greek" },
    { label: "Yamato", value: "yamato" },
    { label: "Celt", value: "celt" },
    { label: "Egyptian", value: "egyptian" }
  ],
  subtypes: [
    { label: "Warrior", value: "warrior" },
    { label: "Yokai", value: "yokai" },
    { label: "Fae", value: "fae" },
    { label: "Beast", value: "beast" },
    { label: "Scholar", value: "scholar" },
    { label: "Onmyoji", value: "onmyoji" },
    { label: "Shikigami", value: "shikigami" },
	{ label: "Argonaut", value: "argonaut" },
  ]
};

// Export for use in other pages
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { cardsData, filterConfig };
}